---
- name: Install bind9
  ansible.builtin.apt:
    pkg: ['bind9', 'bind9utils', 'dnsutils', 'bind9-doc']
    update_cache: yes
  notify: bind9-restart
- name: Configure bind9
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: bind9-restart
